language: python

sudo: true

os: linux

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pylint
  - git clone https://github.com/pydicom/pydicom && cd pydicom && python setup.py install
  - cd $TRAVIS_BUILD_DIR/
  - python setup.py sdist
  - python setup.py install
  - pylint --version

script:
  - python -m unittest discover -s $TRAVIS_BUILD_DIR/deid/tests/ -p '[t|T]est*.py'
