language: python

sudo: true

os: linux

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pylint
  - pip install git+git://github.com/pydicom/pydicom.git@affb1cf10c6be2aca311c29ddddc622f8bd1f810
  - cd $TRAVIS_BUILD_DIR/
  - python setup.py sdist
  - python setup.py install
  - pylint --version

script:
  - python -m unittest discover -s $TRAVIS_BUILD_DIR/deid/tests/ -p '[t|T]est*.py'
